DATASET_PATH = '/Users/zulli/Documents/PhySketch/PhySketch/Dataset'
DATASET_ORIGINAL = 'PhySketchOriginal'
DATASET_PATH_LIST =['/Users/zulli/Documents/PhySketch/PhySketch/experiments/Dataset']
ANNOTATION_DIR = 'annotated'
ANNOTATION_DARKFLOW_DIR = 'annotation-darkflow'
CROPPED_DIR = 'cropped'
AUDIT_DIR = 'annotated/audit'
ANNOTATION_BKP_DIR = 'annotated/bkp'

SCENE_GEN_BACKGROUND_PATH = '/Users/zulli/Documents/PhySketch/PhySketch/experiments/scene-background'

SCENE_GEN_ELEMENT_CHANCE = 0.5


'''SCENE GENERATION - PRIMITIVES'''
SG_PRIMITIVE_MAX_SCALE_UB = 3.0
SG_PRIMITIVE_MIN_SCALE_UB = 2.0

SG_PRIMITIVE_MAX_SCALE_LB = 2.0
SG_PRIMITIVE_MIN_SCALE_LB = 0.9

SG_PRIMITVE_MIN_AREA = 0.04
SG_PRIMITVE_MAX_AREA = 0.2

SG_PRIMITIVE_MAX_DISTORT = 0.2


'''SCENE GENERATION - LINE_COMMANDS'''

SG_L_COMMAND_MAX_SCALE_UB = 2.5
SG_L_COMMAND_MIN_SCALE_UB = 1.2

SG_L_COMMAND_MAX_SCALE_LB = 2.1
SG_L_COMMAND_MIN_SCALE_LB = 0.9

SG_L_COMMAND_MIN_AREA = 0.06
SG_L_COMMAND_MAX_AREA = 0.25

SG_L_COMMAND_MAX_DISTORT = 0.2


'''SCENE GENERATION - POINT_COMMANDS'''

SG_P_COMMAND_MAX_SCALE_UB = 2.8
SG_P_COMMAND_MIN_SCALE_UB = 1.5

SG_P_COMMAND_MAX_SCALE_LB = 2.1
SG_P_COMMAND_MIN_SCALE_LB = 0.9

SG_P_COMMAND_MIN_AREA = 0.04
SG_P_COMMAND_MAX_AREA = 0.1

SG_P_COMMAND_MAX_DISTORT = 0.2

SG_MIN_ELEMENT = 4
SG_MAX_ELEMENT = 15


CIRCLE_PRECISION = 10

SG_MIN_SCENE_SIZE = 700
SG_MAX_SCENE_SIZE = 1800
