DATASET_PATH = '/Users/zulli/Desktop/PhySketch/Dataset'

SCENE_GEN_ELEMENT_CHANCE = 0.4
SCENE_GEN_PRIMITIVE_MAX_SCALE = 1.4
SCENE_GEN_PRIMITIVE_MIN_SCALE = 0.9
SCENE_GEN_PRIMITIVE_MIN_LEGNTH = 100

SCENE_GEN_COMMAND_MAX_SCALE = 1.2
SCENE_GEN_COMMAND_MIN_SCALE = 0.4
SCENE_GEN_COMMAND_MIN_LEGNTH = 100


CIRCLE_PRECISION = 10