MODE_CROPPER_STR = "CROPPER - "
MODE_ANNOTATOR_STR = "ANNOTATOR - "
MODE_VIEWER_STR = "ANNOTATOR - "

MODE_STR = ""
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
IMAGEM_RECORTADA_STR = 'Imagem Recortada - '
IMAGEM_ORIGINAL_STR = "Imagem Original - "
START_AT = 0


TIPO_CIRCULO =  1
TIPO_QUADRADO = 2
TIPO_TRI_EQUI = 3
TIPO_TRI_RET =  4
TIPO_TRI_ESC =  5
TIPO_P_FIXO =   6
TIPO_VETOR =    7
TIPO_CORDA =    8
TIPO_P_ROTA =   9

ANOT_TIPO_STR = "TYPE"
ANOT_TIPO_CIRCULO_STR = "CIRCLE"
ANOT_TIPO_QUAD_STR = "QUAD"
ANOT_TIPO_TRI_EQUI_STR = "TRIANGLE.EQUI"
ANOT_TIPO_TRI_RET_STR = "TRIANGLE.RECT"
ANOT_TIPO_TRI_ESCA_STR = "TRIANGLE.ESCA"
ANOT_TIPO_P_FIXO = "P.FIXO"
ANOT_TIPO_VETOR = "VECTOR"
ANOT_TIPO_CORDA = "ROPE"
ANOT_TIPO_P_ROTA = "P.ROTA"

ANOT_PARENT = "PARENT"

ANOT_COLLECTED_POINTS_STR = "COLLECTED POINTS"
ANOT_CENTER = "CENTER"
ANOT_RADIUS = "RADIUS"
ANOT_LENGHT = "LENGTH"
ANOT_THETA = "THETA"

ANOT_CLASS = "CLASS"
ANOT_PRIMITIVE = "PRIMITIVE"
ANOT_COMMAND = "COMMAND"


ANOT_CATEGORY = "CATEGORY"
ANOT_SCENE = "SCENE"
ANOT_ELEMENT = "ELEMENT"

ANOT_ELEMENT_LIST = "ELEMENTS"
ANOT_DESCRIPTOR = "DESCRIPTOR"
ANOT_P1 = "P1"
ANOT_P2 = "P2"
ANOT_P3 = "P3"